import { Inter } from "next/font/google";
import "./globals.css";
import Banner from "./ui/Banner/Banner";
import Navbar from "./ui/Navbar/Navbar";
import MobileNav from "./ui/Navbar/MobileNav";
import Newsletter from "./ui/Newsletter/Newsletter";
import Footer from "./ui/Footer/Footer";
import CartContextProvider from "@/context/CartContext";
import DrawersContextProvider from "@/context/DrawersContext";
import FlyoutCart from "./ui/FlyoutCart/FlyoutCart";
import { fetchWhishlist } from "./lib/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Elegant Store",
    description: "Ecommerce website generated by Nextjs",
};

export default async function RootLayout({ children }) {
    const wishlist = await fetchWhishlist();
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Banner />
                <CartContextProvider>
                    <DrawersContextProvider>
                        <Navbar />
                        <FlyoutCart />
                        <MobileNav wishlist={wishlist} />
                        {children}
                    </DrawersContextProvider>
                </CartContextProvider>
                <Newsletter />
                <Footer />
            </body>
        </html>
    );
}
