import { Inter } from "next/font/google";
import "./globals.css";
import Banner from "./ui/Banner/Banner";
import Navbar from "./ui/Navbar/Navbar";
import MobileNav from "./ui/Navbar/MobileNav";
import Newsletter from "./ui/Newsletter/Newsletter";
import Footer from "./ui/Footer/Footer";
import AuthContextProvider from "@/context/AuthContext";
// import CartContextProvider from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <AuthContextProvider>
                    {/* <CartContextProvider> */}
                    <Banner />
                    <Navbar />
                    <MobileNav />
                    {children}
                    {/* </CartContextProvider> */}
                </AuthContextProvider>
                <Newsletter />
                <Footer />
            </body>
        </html>
    );
}
